version: 0.12.2-dev.2
tag_template: v{{ yeyo_version }}
commit_template: v{{ yeyo_version }}
files:
- file_path: VERSION
  match_template: yeyo_version
- file_path: docker-compose.yml
  match_template: yeyo_version
- file_path: docs/index.md
  match_template: yeyo_version
- file_path: gcgc/__init__.py
  match_template: yeyo_version
- file_path: pyproject.toml
  match_template: yeyo_version
