# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - docker-compose run --rm gcgc fmt-check
      - docker-compose run --rm gcgc pydocstyle
      - docker-compose run --rm gcgc pylint
      - docker-compose run --rm gcgc test
